@host = http://localhost:3000


GET {{host}}/api/posts

###
POST {{host}}/api/posts

{
    "titulo": "Victoria agonica del Madrid", 
    "descripcion": "El Madrid ganó la Champions en el último minuto",
    "fecha_creacion": "2024-11-17",
    "categoria": "noticia",
    "author_id": 1
}

### 
GET {{host}}/api/authors

###
POST {{host}}/api/authors
Content-Type: application/json

{
    "nombre": "Jose Vila",
    "email": "jose.vila@email.com",
    "imagen": "https://example.com/images/jose.jpg" 
}
